"""DRF filter backends for flex-fields.

Provides two backends:

- ``FlexFieldsDocsFilterBackend`` — a no-op backend whose only purpose is to
  inject the ``fields``, ``omit``, and ``expand`` query parameters into the
  generated API schema (e.g. drf-spectacular / drf-yasg).  Downstream projects
  normally shouldn't use this.

- ``FlexFieldsFilterBackend`` — extends the docs backend with actual queryset
  optimisation: it resolves the active field selection and expansion options
  and applies ``only()`` / ``select_related()`` / ``prefetch_related()`` to
  the queryset automatically.
"""

from functools import lru_cache
import importlib
from typing import Any, Optional, TYPE_CHECKING

from django.core.exceptions import FieldDoesNotExist
from django.db import models
from django.db.models import QuerySet
from rest_framework import serializers
from rest_framework.filters import BaseFilterBackend

if TYPE_CHECKING:
    from rest_framework.viewsets import GenericViewSet
    from rest_framework.request import Request

from .config import (
    EXPAND_PARAM,
    FIELDS_PARAM,
    OMIT_PARAM,
    WILDCARD_VALUES,
)
from .serializers import FlexFieldsSerializerMixin

WILDCARD_VALUES_JOINED = ",".join(WILDCARD_VALUES or [])


class FlexFieldsDocsFilterBackend(BaseFilterBackend):
    """No-op filter backend that adds flex-fields parameters to the API schema.

    Does not modify the queryset.  Its sole purpose is to expose the
    ``fields``, ``omit``, and ``expand`` query parameters in the OpenAPI
    schema generated by tools such as drf-spectacular. Downstream projects
    normally shouldn't use this; use ``FlexFieldsFilterBackend`` instead.
    """

    def filter_queryset(self, request, queryset, view):
        """Return `queryset` unchanged."""
        return queryset

    @staticmethod
    @lru_cache()
    def _get_model_field(field_name: str, model: models.Model) -> Optional[models.Field]:
        """Return the Django model field for `field_name`, or ``None``.

        Result is cached per ``(field_name, model)`` pair via ``lru_cache``.
        Returns ``None`` when the field does not exist on the model (e.g. for
        serializer-only or method fields).
        """
        try:
            # noinspection PyProtectedMember
            return model._meta.get_field(field_name)
        except FieldDoesNotExist:
            return None

    @classmethod
    def _get_expandable_fields(
        cls, serializer_class: Any, parents: tuple = (), prefix: str = ""
    ) -> list:
        """Return a flat list of all expandable field paths for `serializer_class`.

        Traverses nested `FlexFieldsSerializerMixin` subclasses recursively
        and builds dot-separated paths (e.g. ``['author', 'author.profile']``).
        Lazy string serializer paths are resolved before traversal.
        """
        if serializer_class in parents:
            # Break endless recursion
            return []

        meta = getattr(serializer_class, "Meta", None)

        if meta is not None and hasattr(meta, "expandable_fields"):
            expandable_fields_dict = meta.expandable_fields
        elif hasattr(serializer_class, "expandable_fields"):
            expandable_fields_dict = serializer_class.expandable_fields
        else:
            return []

        expandable_fields = list(expandable_fields_dict.items())
        expand_list = []

        while expandable_fields:
            key, field_options = expandable_fields.pop()

            if isinstance(field_options, tuple):
                nested_serializer_class = field_options[0]
            else:
                nested_serializer_class = field_options

            if isinstance(nested_serializer_class, str):
                nested_serializer_class = FlexFieldsDocsFilterBackend._get_serializer_class_from_lazy_string(
                    nested_serializer_class
                )

            expand_list.append(f"{prefix}{key}")

            expand_list += cls._get_expandable_fields(
                serializer_class = nested_serializer_class,
                parents          = parents + (serializer_class,),
                prefix           = f"{prefix}{key}.",
            )

        return expand_list

    @staticmethod
    def _get_serializer_class_from_lazy_string(full_lazy_path: str):
        """Resolve a dotted string path to a serializer class.

        Tries the exact path first; if that fails and the path does not
        already end in ``.serializers``, appends ``.serializers`` and retries.
        Raises ``Exception`` when the class cannot be found.
        """
        def _import_serializer_class(path: str, class_name: str):
            """Import `class_name` from the module at `path`."""
            try:
                module = importlib.import_module(path)
            except ImportError:
                return None

            serializer_class = getattr(module, class_name, None)

            if isinstance(serializer_class, type) and issubclass(serializer_class, serializers.Serializer):
                return serializer_class

            return None

        path_parts = full_lazy_path.split(".")
        class_name = path_parts.pop()
        path = ".".join(path_parts)

        serializer_class = _import_serializer_class(path, class_name)
        if serializer_class is None and not path.endswith(".serializers"):
            serializer_class = _import_serializer_class(
                f"{path}.serializers", class_name
            )

        if serializer_class:
            return serializer_class

        raise Exception(f"Could not resolve serializer class '{class_name}' from path '{path}'.")

    @staticmethod
    def _get_serializer_fields(serializer_class):
        """Return a comma-joined string of the field names declared on `serializer_class`.

        Reads ``Meta.fields`` and converts it into an example-friendly string
        for schema generation. Returns an empty string for ``"__all__"`` or
        unsupported field declarations.
        """
        meta = getattr(serializer_class, "Meta", None)

        if meta is not None and hasattr(meta, "fields"):
            fields = getattr(serializer_class.Meta, "fields", [])

            if isinstance(fields, str):
                return "" if fields == "__all__" else fields

            if isinstance(fields, (list, tuple)):
                serializer_fields = [field_name for field_name in fields if isinstance(field_name, str)]
                return ",".join(serializer_fields)

            return ""
        else:
            return ""

    def get_schema_operation_parameters(self, view):
        """Return the OpenAPI query parameter definitions for the flex-fields params.

        Emits ``fields``, ``omit``, and ``expand`` parameter objects for the
        view's serializer when it is a `FlexFieldsSerializerMixin` subclass.
        Returns an empty list for views that do not use flex fields.
        """
        serializer_class = view.get_serializer_class()

        if not issubclass(serializer_class, FlexFieldsSerializerMixin):
            return []

        fields = self._get_serializer_fields(serializer_class)
        expandable_fields = self._get_expandable_fields(serializer_class)
        expandable_fields.extend(WILDCARD_VALUES or [])

        parameters = [
            {
                "name": FIELDS_PARAM,
                "required": False,
                "in": "query",
                "description": "Specify required fields by comma",
                "schema": {
                    "title": "Selected fields",
                    "type": "string",
                },
                "example": (fields or "field1,field2,nested.field") + "," + WILDCARD_VALUES_JOINED,
            },
            {
                "name": OMIT_PARAM,
                "required": False,
                "in": "query",
                "description": "Specify omitted fields by comma",
                "schema": {
                    "title": "Omitted fields",
                    "type": "string",
                },
                "example": (fields or "field1,field2,nested.field") + "," + WILDCARD_VALUES_JOINED,
            },
            {
                "name": EXPAND_PARAM,
                "required": False,
                "in": "query",
                "description": "Select fields to expand",
                "style": "form",
                "explode": False,
                "schema": {
                    "title": "Expanded fields",
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": expandable_fields
                    }
                },
            },
        ]

        return parameters


class FlexFieldsFilterBackend(FlexFieldsDocsFilterBackend):
    """Filter backend that optimises querysets based on the active flex-fields options.

    Extends `FlexFieldsDocsFilterBackend` with actual queryset manipulation:
    applies ``only()`` to restrict fetched columns and ``select_related()`` and
    ``prefetch_related()`` for expanded relation fields.  Only active for ``GET``
    requests on views whose serializer is a ``FlexFieldsSerializerMixin`` subclass.

    View-level opt-out attributes:

    - ``auto_remove_fields_from_query`` (default ``True``): disable ``only()`` optimisation.
    - ``auto_select_related_on_query`` (default ``True``): disable relation prefetching.
    - ``required_query_fields`` (default ``[]``): extra field names always included in the ``only()`` call.
    """
    def filter_queryset(
        self, request: "Request", queryset: "QuerySet", view: "GenericViewSet"
    ):
        """Apply field-selection and relation-prefetch optimisations to `queryset`.

        Resolves the active ``fields`` / ``omit`` / ``expand`` options from
        the request, then calls ``only()``, ``select_related()``, and
        ``prefetch_related()`` as appropriate.  Returns `queryset` unchanged
        when the view's serializer is not a `FlexFieldsSerializerMixin`
        subclass, or when the request method is not ``GET``.
        """
        # Early exit: only process GET requests on flex-fields serializers.
        if not issubclass(view.get_serializer_class(), FlexFieldsSerializerMixin) or request.method != "GET":
            return queryset

        # Retrieve view-level configuration for query optimisation.
        auto_remove_fields_from_query = getattr(view, "auto_remove_fields_from_query", True)
        auto_select_related_on_query = getattr(view, "auto_select_related_on_query", True)
        required_query_fields = list(getattr(view, "required_query_fields", []))

        # Instantiate serializer and apply active flex-fields options.
        serializer = view.get_serializer(context=view.get_serializer_context()) # type: FlexFieldsSerializerMixin
        serializer.apply_flex_fields(serializer.fields, serializer._flex_options_rep_only)
        serializer._flex_fields_rep_applied = True

        # Classify model fields: regular fields and nested relations.
        model_fields = []
        nested_model_fields = []

        for field in serializer.fields.values():
            model_field = self._get_model_field(field.source, queryset.model)

            if model_field:
                model_fields.append(model_field)

                if (
                    (field.field_name in serializer.expanded_fields) or
                    (model_field.is_relation and not model_field.many_to_one) or
                    (model_field.is_relation and model_field.many_to_one and not model_field.concrete)
                ):  # Include GenericForeignKey
                    nested_model_fields.append(model_field)

        # Optimise queryset: restrict fetched columns via only().
        if auto_remove_fields_from_query:
            queryset = queryset.only(
                *(
                    required_query_fields
                    + [
                        model_field.name
                        for model_field in model_fields if (
                            not model_field.is_relation or
                            model_field.many_to_one and model_field.concrete)
                    ]
                )
            )

        # Optimise queryset: prefetch relations via select_related() and prefetch_related().
        if auto_select_related_on_query and nested_model_fields:
            queryset = queryset.select_related(
                *(
                    model_field.name
                    for model_field in nested_model_fields if (
                            model_field.is_relation and
                            model_field.many_to_one and
                            model_field.concrete)  # Exclude GenericForeignKey
                )
            )

            queryset = queryset.prefetch_related(
                *(
                    model_field.name
                    for model_field in nested_model_fields if
                        (model_field.is_relation and not model_field.many_to_one) or
                        (model_field.is_relation and model_field.many_to_one and not model_field.concrete)  # Include GenericForeignKey)
                )
            )

        return queryset

