name: "Setup CI environment"
description: "Set up Python, Poetry, and optionally Node.js for CI workflows"

inputs:
    # ====== #
    # Python #
    # ====== #
    setup-python:
        description: "Whether to set up Python"
        required: false
        default: "true"

    python-version:
        description: "Python version to install"
        required: false
        default: "3.14"

    poetry-version:
        description: "Poetry version to install"
        required: false
        default: "latest"

    # === #
    # Git #
    # === #
    configure-git-author:
        description: "Whether to configure the Git author as the github-actions bot"
        required: false
        default: "false"

runs:
    using: "composite"
    steps:
        # ====== #
        # Python #
        # ====== #
        - name: "Install Poetry"
          if: ${{ inputs.setup-python == 'true' }}
          uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1
          with:
              version: ${{ inputs.poetry-version }}

        - name: "Set up Python"
          if: ${{ inputs.setup-python == 'true' }}
          uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
          with:
              python-version: ${{ inputs.python-version }}
              cache: "poetry"

        - name: "Install Python dependencies"
          if: ${{ inputs.setup-python == 'true' }}
          # Floating poetry version can trigger "lockfile too old". As a workaround (since Poetry
          # versions locally in CI can always differ), we run `poetry lock` to regenerate it.
          run: |-
            rm -f poetry.lock
            poetry lock
            poetry install --no-interaction --no-root --with dev
          shell: bash

        # === #
        # Git #
        # === #
        - name: "Configure Git author"
          if: ${{ inputs.configure-git-author == 'true' }}
          shell: bash
          run: |
              git config user.name "github-actions[bot]"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
